blank_issues_enabled: false
contact_links:
- name: 💬 Discord
  url: https://discord.gg/wFsfhJh4Rh
  about: |
    For any other help or just discussion. 
    
- name: Telegram
  url: https://t.me/techtanic
  about: |
    For any other help or just discussion. 
